language: shell

addons:
  homebrew:
    packages:
    update: false

stages:
  - name: "No dependencies" # Doesn't depend on anything apart from upstream packages
    if: type != cron

jobs:
 include:
  - stage: "No dependencies"
    os: linux
    dist: xenial
    env:
    - PACKAGE=misc/magic
  - stage: "No dependencies"
    os: linux
    dist: xenial
    env:
    - PACKAGE=misc/magic BUILDONLY_CHANNELS=conda-forge

before_install:
 - source $TRAVIS_BUILD_DIR/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/common.sh

install:
 - bash $TRAVIS_BUILD_DIR/.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

cache:
  directories:
   - $HOME/.conda/pkgs
