language: shell

addons:
  homebrew:
    packages:
    update: false

stages:
  - "EDA Tools - Bitstream"
  - "EDA Tools - Simulation"
  - "EDA Tools - Synthesis"
  - "EDA Tools - PnR"
  - "EDA Tools - Formal"
  - "EDA Tools - Xilinx Vivado metapackages"

jobs:
 include:
  - stage: "EDA Tools - Bitstream"
    os: windows
    env:
    - PACKAGE=bit/prjtrellis
 # EDA Tools - Simulation
  # Linux
  - stage: "EDA Tools - Simulation"
    os: linux
    dist: xenial
    env:
    - PACKAGE=sim/icarus
  - stage: "EDA Tools - Simulation"
    os: linux
    dist: xenial
    env:
    - PACKAGE=sim/verilator
  # Windows
  - stage: "EDA Tools - Simulation"
    os: windows
    env:
    - PACKAGE=sim/icarus
  # OSX
  - stage: "EDA Tools - Simulation"
    os: osx
    osx_image: xcode8.3
    env:
    - PACKAGE=sim/icarus
  - stage: "EDA Tools - Simulation"
    os: osx
    osx_image: xcode8.3
    env:
    - PACKAGE=sim/verilator

 # EDA Tools - Synthesis
  # Linux
  - stage: "EDA Tools - Synthesis"
    os: linux
    dist: xenial
    env:
    - PACKAGE=syn/yosys
  # Windows
  - stage: "EDA Tools - Synthesis"
    os: windows
    env:
    - PACKAGE=syn/yosys
  # OSX
  - stage: "EDA Tools - Synthesis"
    os: osx
    osx_image: xcode8.3
    env:
    - PACKAGE=syn/yosys EXTRA_BUILD_ARGS="--no-test"

 # EDA Tools - Place and Route
  # Linux
  - stage: "EDA Tools - PnR"
    os: linux
    dist: xenial
    env:
    - PACKAGE=pnr/arachne
  - stage: "EDA Tools - PnR"
    os: linux
    dist: xenial
    env:
    - PACKAGE=pnr/nextpnr/ice40
  - stage: "EDA Tools - PnR"
    os: linux
    dist: xenial
    env:
    - PACKAGE=pnr/nextpnr/ecp5
  - stage: "EDA Tools - PnR"
    os: linux
    dist: xenial
    env:
    - PACKAGE=pnr/nextpnr/generic
  - stage: "EDA Tools - PnR"
    os: linux
    dist: xenial
    env:
    - PACKAGE=pnr/vtr
  # Windows
  - stage: "EDA Tools - PnR"
    os: windows
    env:
    - PACKAGE=pnr/nextpnr/ice40
  - stage: "EDA Tools - PnR"
    os: windows
    env:
    - PACKAGE=pnr/nextpnr/generic
  # OSX
  - stage: "EDA Tools - PnR"
    os: osx
    osx_image: xcode8.3
    env:
    - PACKAGE=pnr/nextpnr/ice40
  - stage: "EDA Tools - PnR"
    os: osx
    osx_image: xcode8.3
    env:
    - PACKAGE=pnr/vtr
  - stage: "EDA Tools - PnR"
    os: osx
    osx_image: xcode8.3
    env:
    - PACKAGE=pnr/nextpnr/generic

 # EDA Tools - Formal
  - stage: "EDA Tools - Formal"
    env:
    - PACKAGE=formal/symbiyosys

 # EDA Tools - Xilinx Vivado metapackages
  - stage: "EDA Tools - Xilinx Vivado metapackages"
    os: linux
    dist: xenial
    env:
      - PACKAGE=xilinx/vivado
      - VERSIONS=$TRAVIS_BUILD_DIR/xilinx/vivado/versions
    script:
      - bash $TRAVIS_BUILD_DIR/xilinx/vivado/gen_metapackages.sh
    after_success:
      - echo "Xilinx Vivado metapackages built for versions:" && cat $VERSIONS

 allow_failures:
  - stage: "EDA Tools - PnR"
    os: windows
    env:
    - PACKAGE=pnr/nextpnr/ice40
  - stage: "EDA Tools - PnR"
    os: osx
    env:
    - PACKAGE=pnr/vtr
  - stage: "EDA Tools - Simulation"
    os: windows
    env:
    - PACKAGE=sim/icarus

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - bash $TRAVIS_BUILD_DIR/.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
