{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X.X', GIT_DESCRIBE_NUMBER|int,   GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: uhdm-integration-yosys
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/alainmarcel/uhdm-integration.git

requirements:
  run:
    - surelog-uhdm
    - yosys-uhdm
