{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: symbiflow-toolchain-xray
  version: {{ version }}

source:
  git_url: https://github.com/SymbiFlow/conda-packages.git
  git_rev: master

requirements:
  run:
    - symbiflow-vtr
    - symbiflow-yosys
    - symbiflow-yosys-plugins

about:
  summary: 'Conda metapackage combining VtR, Yosys and Yosys plugins.'
