package:
  name: antmicro-yosys-plugins
  version: 0.0

source:
  git_url: https://github.com/antmicro/ibex-yosys-build.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - antmicro-yosys
    - make
  host:
    - iverilog
    - antmicro-yosys
  run:
    - antmicro-yosys

