# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}
{% set python = '3.8.*' %}

package:
  name: surelog
  version: {{ version }}

source:
  git_url: https://github.com/alainmarcel/Surelog
  git_rev: master

build:
  number: {{ environ.get('DATE_NUM') }}
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake
    - pkg-config
    - libuuid
    - gperftools
    - flex
    - libunwind
    - swig

  run:
    - python {{ python }}
    - gperftools
    - libunwind

about:
  home: https://github.com/alainmarcel/Surelog
  license: Apache
  license_file: LICENSE
  summary: 'Parser/Compiler for SystemVerilog'
