{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X.X', GIT_DESCRIBE_NUMBER|int,   GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: yosys-uhdm
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/alainmarcel/uhdm-integration.git

build:
  script_env:
    - CI
    - TRAVIS
    - USE_SYSTEM_GCC_VERSION

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake
    - pkg-config
    - libuuid
    - gperftools
    - flex
    - libunwind
    - swig
    - ncurses
test:
    requires:
        - ncurses
        - readline
        - libffi
    commands:
        - yosys-uhdm --version
