name: build-packages
on: [push, pull_request]
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 68
defaults:
  run:
    shell: bash
jobs:

  yosys-uhdm-linux-py38:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "syn/yosys-uhdm"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master
