name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 71
defaults:
  run:
    shell: bash
jobs:
  #56
  surelog-uhdm-linux-py37:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #67
  surelog-uhdm-linux-py38:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  surelog-uhdm-verilator-linux-py37:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm-verilator"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #67
  surelog-uhdm-verilator-linux-py38:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm-verilator"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  surelog-uhdm-yosys-linux-py37:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm-yosys"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #67
  surelog-uhdm-yosys-linux-py38:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm-yosys"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #57
  yosys-uhdm-linux-py37:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "syn/yosys-uhdm"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #68
  yosys-uhdm-linux-py38:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "syn/yosys-uhdm"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #58
  verilator-uhdm-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sim/verilator-uhdm"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #59
  uhdm-integration-verilator-linux-py37:
    runs-on: "ubuntu-16.04"
    needs: ["surelog-uhdm-verilator-linux-py37", "verilator-uhdm-linux"]
    env:
      PACKAGE: "sim/uhdm-integration-verilator"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      # Skip if token isn't available (cross-repository PRs mainly)
      - run: if [ "$ANACONDA_TOKEN" = "" ]; then echo "SKIP=true" >>$GITHUB_ENV; fi
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #70
  uhdm-integration-verilator-linux-py38:
    runs-on: "ubuntu-16.04"
    needs: ["surelog-uhdm-verilator-linux-py38", "verilator-uhdm-linux"]
    env:
      PACKAGE: "sim/uhdm-integration-verilator"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      # Skip if token isn't available (cross-repository PRs mainly)
      - run: if [ "$ANACONDA_TOKEN" = "" ]; then echo "SKIP=true" >>$GITHUB_ENV; fi
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #60
  uhdm-integration-yosys-linux-py37:
    runs-on: "ubuntu-16.04"
    needs: ["surelog-uhdm-yosys-linux-py37", "yosys-uhdm-linux-py37"]
    env:
      PACKAGE: "sim/uhdm-integration-yosys"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      # Skip if token isn't available (cross-repository PRs mainly)
      - run: if [ "$ANACONDA_TOKEN" = "" ]; then echo "SKIP=true" >>$GITHUB_ENV; fi
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #71
  uhdm-integration-yosys-linux-py38:
    runs-on: "ubuntu-16.04"
    needs: ["surelog-uhdm-yosys-linux-py38", "yosys-uhdm-linux-py38"]
    env:
      PACKAGE: "sim/uhdm-integration-yosys"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      # Skip if token isn't available (cross-repository PRs mainly)
      - run: if [ "$ANACONDA_TOKEN" = "" ]; then echo "SKIP=true" >>$GITHUB_ENV; fi
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master
