name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 71
defaults:
  run:
    shell: bash
jobs:
  #14
  vtr-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "pnr/vtr"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master
  #19
  quicklogic-vtr-linux:
    runs-on: "ubuntu-16.04"
    needs: "vtr-linux"
    env:
      PACKAGE: "pnr/quicklogic-vtr"
      OS_NAME: "linux"
    steps:
      # Skip if token isn't available (cross-repository PRs mainly)
      - run: if [ "$ANACONDA_TOKEN" = "" ]; then echo "SKIP=true" >>$GITHUB_ENV; fi
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master
